### ISSUE TITLE
Image is broken in asset site

### ISSUE THREAD

**Issue by noah-art3mis** [rakugoteam/Emojis-For-Godot#9]
**Describe the bug**
The screenshot of the editor is broken. 

**To Reproduce**
1. Go to https://godotengine.org/asset-library/asset/1048
2. The image does not work https://raw.githubusercontent.com/rakugoteam/Emojis-For-Godot/main/screenshot.png

**Additional context**
It would show where to find the EmojiFinder in the toolbar. Without this, it is hard to use the addon effectively.

**Comment by Jeremi360** [comment]
@noah-art3mis
Sorry, but I had 3 big problems with Godot Asset Lib:
- awful long waiting time for acceptance for any change in add-on
- I couldn't remove my old addons
- I couldn't change my nickname

So I stopped to upload there new versions, here you can download newest version:
https://github.com/rakugoteam/Emojis-For-Godot/releases
To update go to *addons* folder in your remove current *emojis-for-godot* dir.
Then from downloaded zip upack *addons/emojis-for-godot* dir in to project *addons* dir.
[And also read this repo README to see base info about addon.](https://github.com/rakugoteam/Emojis-For-Godot#readme)
After this addon should be in Top Editor Menu as *Project -> Tools -> Emoji Finder*.
